version: '3'

services:
  redis:
    container_name: redis
    image: redis:7
    command: redis-server
    ports:
      - "6379:6379"

  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
