version: '3'

services:
  redis:
    container_name: redis
    image: redis:7
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - network

  app-server:
    container_name: app-server
    build: app-server
    restart: always
    env_file: 
      - app-server/.env
    depends_on:
      - redis
    ports:
      - "8080:8080"
    networks:
      - network
    links:
      - redis

networks:
  network:
