version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@3.1.1

on-release: &on-release
  filters:
    tags:
      only: /^v.*/

executors:
  with-workspace:
    resource_class: small
    docker:
      - image: cimg/base:2023.09
    working_directory: ~/workspace

jobs:
  build:
    executor: with-workspace
    steps:
      - checkout

      - run:
          command: echo $CIRCLE_TAG

      - run:
          name: Build Docker image
          command: docker build -t jl-app-server:$CIRCLE_TAG app-server

      - run:
          name: Tag Docker image
          command: docker tag jl-app-server:$CIRCLE_TAG asia-northeast1-docker.pkg.dev/just-links-dotdev/jl-app-servers/jl-app-server:$CIRCLE_TAG

      - persist_to_workspace:
          root: .
          paths:
            - app-server

  push:
    executor: gcp-cli/google
    working_directory: ~/workspace
    steps:
      - attach_workspace:
          at: ~/workspace

      - checkout

      - gcp-cli/setup

      - run:
          name: Push Docker image to GCP Artifact Registry
          command: |
            gcloud auth configure-docker asia-northeast1-docker.pkg.dev
            docker push asia-northeast1-docker.pkg.dev/just-links-dotdev/jl-app-servers/jl-app-server:$CIRCLE_TAG

workflows:
  build-and-push:
    jobs:
      - build:
          <<: [*on-release]
      - push:
          requires:
            - build
          <<: [*on-release]
