[package]
name = "app-server"
version = "0.0.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
nanoid = "0.4"
dotenvy = "0.15"
rand = "0.8"
futures = "0.3.28"

axum = { version = "0.6", features = ["headers", "macros"] }
axum-extra={ version = "0.7", features = ["cookie"] }
tower = "0.4"
tower-http = { version = "0.4", features = ["cors", "timeout", "trace"] }
async-session = "3.0.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
biscuit = "0.6.0"

pockety = { path = "../../pockety/pockety" }
time = "0.3.23"

