name: Build and Deploy web frontend to Cloudflare Pages

on:
  push:
    tags:
      - "web-v[0-9]+.[0-9]+.[0-9]+"

env:
  PROJECT_NAME: "just-links"
  OUTPUT_DIR: "/web/.svelte-kit/output"

jobs:
  publish:
    permissions:
      contents: read
      deployments: write

    runs-on: ubuntu-latest

    steps:
      - name: Move to web directory
        run: |
          cd web

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Install dependencies
        run: pnpm install

      - name: Build web frontend
        run: pnpm build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: env.PROJECT_NAME
          directory: env.OUTPUT_DIR
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
