name: Build and Deploy web frontend to Cloudflare Pages

on:
  push:
    tags:
      - "web-v[0-9]+.[0-9]+.[0-9]+"

env:
  PROJECT_NAME: "just-links"
  OUTPUT_DIR: "./web/.svelte-kit/cloudflare"
  STORE_PATH: ""

jobs:
  publish:
    permissions:
      contents: read
      deployments: write

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "./web"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Create env file"
        run: |
          echo "${{ secrets.WEB_ENV_FILE }}" > .env

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build web frontend
        run: pnpm build --mode production

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ env.PROJECT_NAME }}
          directory: ${{ env.OUTPUT_DIR }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
